### ISSUE TITLE
HTTPs to api.thingspeak.com

### ISSUE THREAD

**Issue by bittmanv** [khoih-prog/EthernetWebServer_SSL_STM32#2] opened 2022-12-29 16:18 UTC
### Describe the bug

Hi, I identified something like bug during testing of WebSSL Client example.

Example as-is works fine against www.google.com, but doesn't connect to api.thingspeak.com by server name, but connects, when I connect directly to IP 52,204,34,129 in my case, connection is establlished with warning about preference to use server name. 

During debugging, and validation, I found, that CN of api.thingspeak.com certificate is *.thingspeak.com, which is most probably root cause of issue, but I haven't found place, where to reconfigure it.

Just for complete picture. I'm using standard Ethernet.2.0.0 library with my own constructor to pass right SPI instance, which is part of my bigger project 

### Steps to Reproduce

Steps to reproduce the behavior. Including the [MRE](https://stackoverflow.com/help/minimal-reproducible-example) sketches
1) Clone example WebClient_SSL 
2) Generate trust anchors for api.thingspeak.com  
3) configure defines for card 
4) set server_host to api.thingspeak.com
5) compile. run and check serial terminal 

### Expected behavior

Serial will contain Connected to api.thingspeak.com 

### Actual behavior

Connection failed message

When I replace line 

`sslClient.connect(server_host, server_port) `

with 
`sslClient.connect(IPAddress(52,204,34,129), ssl_server_port)`

Connection is established and ssl client works

### Information

Please ensure to specify the following:

* Platform.io  6.1.5 
* Board Core Generic STM32F103RE  ( Bluebutton STM32F103RE  in STM32duino board list) 
* Contextual information trying to replace http with https for posting data to thing speak
* Simplest possible steps to reproduce see steps above
* Anything that might be relevant in your opinion, such as:
  * Operating system Windows 10 22H2 
  * Network configuration 

Context  
Activity is part of my project for Home automation gateway between sensor network based on RFM69/Radiohead and Mqtt/Openhab and Thingspeak ( this is more historical from begining of project). 
Currently I have about 30 nodes in network, with rate about 800+ radio messages/hour

**Comment by khoih-prog** [comment] 2022-12-29 20:10
Hi @bittmanv 

Thanks for using the library. Just have a quick look at

> Example as-is works fine against [www.google.com](http://www.google.com/), but doesn't connect to api.thingspeak.com by server name, but connects, when I connect directly to IP 52,204,34,129 in my case, connection is establlished with warning about preference to use server name.

then

> During debugging, and validation, I found, that **CN of api.thingspeak.com certificate** is *.thingspeak.com, which is most probably root cause of issue, but I haven't found place, where to reconfigure it.

the conclusion is that this is not a bug of this library. You have to post the question on `Thingspeak` or Arduino Forum for help.

I'm closing this issue now, and won't reopen until library's bug could be proven.

Good Luck,

**Closed as completed by khoih-prog** 2022-12-29 20:10 UTC
Labels: Support
